export const ROUTES = {
  HOME:            "/",
  LOGIN:           "/auth/login",
  REGISTER:        "/auth/register",
  AUTH_CALLBACK:   "/auth/callback",
  FORGOT_PASSWORD: "/auth/forgot-password",
  VERIFY_EMAIL:    "/auth/verify-email",
  ONBOARDING:      "/auth/onboarding", 
  DASHBOARD:       "/dashboard",
  RISK_ASSESSMENT: "/profil-risiko",
  PROJECTION:      "/proyeksi",
  RECOMMENDATION:  "/rekomendasi",
  AI_ADVISOR:      "/advisor",
  SETTINGS:        "/pengaturan",
} as const;
